apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet-app.fullname" . }}
  labels:
    app: {{ include "dotnet-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dotnet-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dotnet-app.name" . }}
    spec:
      containers:
      - name: {{ include "dotnet-app.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}